---PARTICIPANT TABLE
    ---200m freestyle swimming
insert into PARTICIPANT values (1, 'Ian', 'Thorpe', 'Australia', 'Australia', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (2, 'Pieter', 'Hoogenband', 'Netherlands', 'Netherlands', to_date('14-MAR-78','DD-MON-RR'));
insert into PARTICIPANT values (3, 'Michael', 'Phelps', 'American', 'USA', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (4, 'Klete', 'Keller', 'American', 'USA', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (5, 'Grant', 'Hackett', 'Australia', 'Australia', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (6, 'Rick', 'Say', 'Canadia', 'Canada', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (7, 'Simon', 'Burnett', 'Britain', 'Britain', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (8, 'Emiliano', 'Brembilla', 'Italy', 'Italy', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (9, 'Tae-Hwan', 'Park', 'Korea', 'Korea', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (10, 'Peter', 'Vanderkaay', 'America', 'USA', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (11, 'Jean', 'Basson', 'South Africa', 'South Africa', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (13, 'Dominik', 'Meichtry', 'Switzerland', 'Switzerland', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (14, 'Okumura', 'Yoshihiro', 'Japan', 'Japan', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (15, 'Robbie', 'Renwick', 'Britain', 'Britain', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (16, 'Yannick', 'Agnel', 'France', 'France', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (17, 'Yang', 'Sun', 'China', 'China', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (18, 'Ryan', 'Lochte', 'America', 'USA', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (19, 'Paul', 'Biedermann', 'Germany', 'Germany', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (20, 'Thomas', 'Fraser-Holmes', 'Australia', 'Australia', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (21, 'Danila', 'Izotov', 'Russia', 'Russia', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (22, 'Chad', 'Clos', 'South Africa', 'South Africa', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (23, 'Conor', 'Dwyer', 'America', 'USA', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (24, 'James', 'Guy', 'Britain', 'Britain', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (25, 'Townley', 'Haas', 'America', 'USA', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (27, 'Hagino', 'Kosuke', 'Japan', 'Japan', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (28, 'Aleksandr', 'Krasnykh', 'Russia', 'Russia', to_date('13-OCT-82','DD-MON-RR'));

---swimming 400m freestyle
insert into PARTICIPANT values (30, 'Massimiliano', 'Rosolino', 'Italy', 'Italy', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (31, 'Yuri', 'Prilukov', 'Russia', 'Russia', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (32, 'Spyridon', 'Gianniotis', 'Greece', 'Greece', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (33, 'Takeshi', 'Matsuda', 'Japan', 'Japan', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (34, 'Zhang', 'Lin', 'China', 'China', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (35, 'Larsen', 'Jensen', 'America', 'USA', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (36, 'Oussama', 'Mellouli', 'Tunisia', 'Tunisia', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (38, 'Nikita', 'Lobintsev', 'Russia', 'Russia', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (39, 'Yun', 'Hao', 'China', 'China', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (40, 'Gergo', 'Kis', 'Hungary', 'Hungary', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (41, 'David', 'Carry', 'Britain', 'Britain', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (42, 'Ryan', 'Napoleon', 'Australia', 'Australia', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (43, 'Mack', 'Horton', 'Australia', 'Australia', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (44, 'Gabriele', 'Detti', 'Italy', 'Italy', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (45, 'Connor', 'Jaeger', 'America', 'USA', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (46, 'David', 'McKeon', 'Australia', 'Australia', to_date('13-OCT-82','DD-MON-RR'));
insert into PARTICIPANT values (47, 'Jordan', 'Pothain', 'France', 'France', to_date('13-OCT-82','DD-MON-RR'));

	---COUNTRY TABLE
insert into COUNTRY values (1, 'China', 'CHN');
insert into COUNTRY values (2, 'United States', 'USA');
insert into COUNTRY values (3, 'Australia', 'AUS');
insert into COUNTRY values (4, 'Korea', 'KOR');
insert into COUNTRY values (5, 'Italy', 'ITA');
insert into COUNTRY values (6, 'Japan', 'JPN');
insert into COUNTRY values (7, 'Georgia', 'GEO');
insert into COUNTRY values (8, 'Mongolia', 'MGL');
insert into COUNTRY values (9, 'Austria', 'AUT');
insert into COUNTRY values (10, 'Uzbekistan', 'UZB');
insert into COUNTRY values (11, 'Netherlands', 'NLD');
insert into COUNTRY values (12, 'Russia', 'RUS');
insert into COUNTRY values (13, 'Brazil', 'BRA');
insert into COUNTRY values (14, 'Kazakhstan', 'KAZ');
insert into COUNTRY values (15, 'Indonesia', 'INA');
insert into COUNTRY values (16, 'Denmark', 'DEN');
insert into COUNTRY values (17, 'Malaysia', 'MAS');
insert into COUNTRY values (18, 'Britain', 'GBR');
insert into COUNTRY values (19, 'Spain', 'ESP');
insert into COUNTRY values (20, 'Argentina', 'ARG');
insert into COUNTRY values (21, 'Czech Republic', 'CZE');
insert into COUNTRY values (22, 'Switzerland', 'CHE');
insert into COUNTRY values (23, 'Chile', 'CHI');
insert into COUNTRY values (24, 'Germany', 'GER');
insert into COUNTRY values (25, 'Croatia', 'CRO');
insert into COUNTRY values (26, 'Slovensko', 'SUI');
insert into COUNTRY values (27, 'France', 'FRA');
insert into COUNTRY values (28, 'Roumania', 'ROU');

insert into COUNTRY values (29, 'Portugal', 'PRT');
insert into COUNTRY values (30, 'Jamaica', 'JAM');
insert into COUNTRY values (31, 'Sain Kitts', 'KNA');
insert into COUNTRY values (32, 'Barbados', 'BRB');
insert into COUNTRY values (33, 'Ghana', 'GHA');
insert into COUNTRY values (34, 'Trinidad and Tobago', 'TTO');
insert into COUNTRY values (35, 'Netherlands Antilles', 'ANT');
insert into COUNTRY values (36, 'South Africa', 'ZAF');
insert into COUNTRY values (37, 'Ivory Coast', 'CIV');
insert into COUNTRY values (38, 'Canada', 'CAN');
insert into COUNTRY values (39, 'India', 'IND');
insert into COUNTRY values (40, 'Sweden', 'SWE');
